name: deploy

on:
  push:
    branches: ["main"]
  schedule:
    - cron: '00 01 * * MON' # every Monday @ 1:00 a.m.
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages:    write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url:  ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Update apt
        run:  sudo apt-get update

      - name: Install gdebi-core
        run:  sudo apt install gdebi --fix-missing

      - name: Download Prince
        run:  wget https://www.princexml.com/download/prince_15-1_ubuntu22.04_amd64.deb

      - name: Install Prince
        run:  sudo gdebi prince_15-1_ubuntu22.04_amd64.deb --non-interactive

      - name: Install dependencies
        run:  npm ci

      - name: Run tests
        run:  npm test

      - name: Build site
        run:  npm run build

      - name: Deploy bibliography
        uses: peaceiris/actions-gh-pages@v3
        if:   ${{ github.ref == 'refs/heads/main' }}
        with:
          enable_jekyll:  true
          exclude_assets: 'index.html'
          github_token:   ${{ secrets.GITHUB_TOKEN }}
          publish_branch: zenodo
          publish_dir:    ./dist/bibliography

      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './dist'

      - name: Deploy to GitHub Pages
        id:   deployment
        uses: actions/deploy-pages@v1
